name: Metrics Data

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  data:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: NVSRahul

          output_action: json
          filename: data/metrics.json

          base: activity
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
